[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "nft"

# /api sin trailing slash
[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200
  force = true

# /api/cualquier/ruta
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true
